---
- name: Install latest datadog-installer package (yum)
  yum:
    name: "{{ datadog_installer_flavor }}"
    update_cache: true
    state: latest # noqa package-latest
  register: datadog_installer_install_result
  ignore_errors: true
