---
- name: Set APM injection languages and versions for Debian
  set fact:
    agent_dd_apm_install_pkg_versions: "{{ (agent_dd_apm_install_pkg_versions | default([], true)) + ['datadog-apm-library-' + (item[0]-item[1] | split(':'))]}}"
  loop: "{{ datadog_apm_instrumentation_lib_versions }}"
  when: datadog_apm_instrumentation_lib_versions or datadog_apm_instrumentation_lib_versions != ["all"]

- name: Set APM injection install packages
  set_fact:
    agent_dd_apm_install_pkgs: "{{ (agent_dd_apm_install_pkgs | default([], true)) + ['datadog-apm-library-' + item] }}"
    package_state: present
  with_items: "{{ datadog_apm_instrumentation_languages }}"
  when: not datadog_apm_instrumentation_lib_versions

- name: Install APM inject libraries (dnf)
  dnf:
    name: "{{ ['datadog-apm-inject'] + (agent_dd_apm_install_pkgs | default([], true)) }}"
    update_cache: true
    state: "{{ (package_state | default('latest')) }}"
  when: not ansible_check_mode and ansible_pkg_mgr == "dnf"

- name: Install APM inject libraries (yum)
  yum:
    name: "{{ ['datadog-apm-inject'] + (agent_dd_apm_install_pkgs | default([], true)) }}"
    update_cache: true
    state: "{{ (package_state | default('latest')) }}"
  when: not ansible_check_mode and ansible_pkg_mgr == "yum"
