---
- name: Create main Datadog agent configuration file
  template:
    src: datadog.conf.j2
    dest: /etc/dd-agent/datadog.conf
    owner: '{{ datadog_user }}'
    group: '{{ datadog_group }}'
  notify: restart datadog-agent

# DEPRECATED: Remove specific handling of the process check for next major release
- name: Add process check configuration
  template: src=process.yaml.j2 dest=/etc/dd-agent/conf.d/process.yaml
  when: datadog_process_checks is defined
  notify: restart datadog-agent

- debug: 'msg="[DEPRECATION NOTICE] Using `datadog_process_checks` is deprecated, use `process` under `datadog_checks` instead"'
  when: datadog_process_checks is defined

- name: Ensure datadog-agent is running
  service: name=datadog-agent state=started enabled=yes
  when: datadog_enabled

- name: Ensure datadog-agent is not running
  service: name=datadog-agent state=stopped enabled=no
  when: not datadog_enabled

- name: Create a configuration file for each Datadog check
  template:
    src: checks.yaml.j2
    dest: /etc/dd-agent/conf.d/{{ item }}.yaml
    owner: '{{ datadog_user }}'
    group: '{{ datadog_group }}'
  with_items: '{{ datadog_checks|list }}'
  notify: restart datadog-agent
