---
- apt_key: id=C7A7DA52 keyserver=keyserver.ubuntu.com state=present

- apt_repository: repo='deb http://apt.datadoghq.com/ stable main' state=present update_cache=yes

- apt: name=datadog-agent state=latest

- name: copy datadog.conf file
  template: src=datadog.conf.j2 dest=/etc/dd-agent/datadog.conf
  notify: restart datadog

- name: copy conf.d files if set
  template: src={{ item }}.j2 dest=/etc/dd-agent/conf.d/{{ item }}
  with_items: 
    - "{{ datadog_conf_d_files }}"
  notify: restart datadog
  when: datadog_conf_d_files is defined

- service: name=datadog-agent state=started

