---
- apt_key: id=C7A7DA52 keyserver=keyserver.ubuntu.com state=present

- apt_repository: repo='deb http://apt.datadoghq.com/ stable main' state=present update_cache=yes

- apt: name=datadog-agent state=latest

- template: src=datadog.conf.j2 dest=/etc/dd-agent/datadog.conf
  notify: restart datadog

- service: name=datadog-agent state=started

