- name: Set DD Username Arg
  set_fact:
    win_install_args: "{{ win_install_args }} DDAGENTUSER_NAME={{ datadog_windows_ddagentuser_name }}"
  when: datadog_windows_ddagentuser_name != ""

- name: Set DD Password Arg
  set_fact:
    win_install_args: "{{ win_install_args }} DDAGENTUSER_PASSWORD={{ datadog_windows_ddagentuser_password }}"
  when: datadog_windows_ddagentuser_password != ""

- name: Set Test
  set_fact:
    win_install_args: "{{ win_install_args }}"