---
- name: Copy repo file into place
  copy: src=datadog.repo dest=/etc/yum.repos.d/datadog.repo owner=root group=root mode=0644

- name: Install datadog-agent package
  yum: name=datadog-agent state=latest

- template: src=datadog.conf.j2 dest=/etc/dd-agent/datadog.conf
  notify: restart datadog

- service: name=datadog-agent state=started

