---
- name: Convert datadog_agent_major_version to string
  set_fact:
    agent_datadog_agent_major_version: "{{ datadog_agent_major_version | default('', true) | string }}"

- name: Initialize skip install flag to false
  set_fact:
    agent_datadog_skip_install: false

- name: Include parse version tasks
  include_tasks: parse-version.yml
  when: datadog_agent_version | default('', true) | length > 0

- name: Fail if specified agent version is above maximum supported by OS
  fail:
    msg: "Agent versions {{ agent_datadog_major }}.{{ datadog_agent_max_version.minor + 1 }} and above not supported by current OS."
  when: datadog_agent_max_version is defined and agent_datadog_minor is defined and agent_datadog_minor | int > datadog_agent_max_version.minor

- name: Set Agent default major version
  set_fact:
    agent_datadog_agent_major_version: "7"
  when: agent_datadog_agent_major_version | length == 0
