---
- name: Set datadog_checks variable
  set_fact:
    agent_datadog_checks: "{{ datadog_checks | default({}, true) }}"

- name: Set datadog_agent_major_version variable
  set_fact:
    agent_datadog_agent_major_version: "{{ datadog_agent_major_version | default('', true) | string }}"

- name: Set datadog_zypper_repo variable
  set_fact:
    agent_datadog_zypper_repo: "{{ datadog_zypper_repo }}"
