---

- hosts: all
  roles:
    - { role: '/root/project/'}
  vars:
    datadog_api_key: "11111111111111111111111111111111"
    datadog_agent_major_version: 5
    datadog_agent_version: "{{ '1:5.32.9-1' if ansible_facts.os_family in ['RedHat', 'Rocky', 'AlmaLinux'] else '1:5.32.8-1' }}"
    datadog_agent_allow_downgrade: yes
    datadog_config:
      tags: "mytag0, mytag1"
      log_level: INFO
      apm_enabled: "true"  # has to be set as a string
    datadog_config_ex:
      trace.config:
        env: dev
      trace.concentrator:
        extra_aggregators: version
    datadog_checks:
      process:
        init_config:
        instances:
          - name: agent
            search_string: ['agent']
