---
- hosts: all
  roles:
    - { role: "/home/circleci/project/" }
  vars:
    datadog_agent_major_version: 7
    datadog_api_key: "11111111111111111111111111111111"
    datadog_apm_instrumentation_enabled: "host"
    datadog_apm_instrumentation_libraries: ["python"]
    datadog_integration:
      datadog-postgres:
        action: install
