---
- hosts: all
  tasks:
    - block:
        - ansible.builtin.include_role:
            name: '/root/project/'
          vars:
            datadog_agent_major_version: 7
            datadog_api_key: "11111111111111111111111111111111"
            datadog_enabled: false
            datadog_skip_running_check: true
            datadog_integration:
              test-integration:
                action: install
                version: 1.0.0
      rescue:
        - name: Integration install failed (expected)
          ansible.builtin.debug:
            msg: "Integration install failed, but that's okay for this test"
      always:
        - name: Verify traditional path was detected
          ansible.builtin.assert:
            that: datadog_agent_binary_path == "/opt/datadog-agent/bin/agent/agent"
            fail_msg: "Wrong path: {{ datadog_agent_binary_path }}"

