---

- hosts: all
  roles:
    - { role: '/root/project/'}
  vars:
    datadog_api_key: "11111111111111111111111111111111"
    datadog_enabled: false
    datadog_skip_running_check: true
    datadog_installer_default_pkg_version: '1:7.54.0~installer~0.0.1-1'
    datadog_agent_version: 7.54.0
    datadog_apm_instrumentation_enabled: host
    datadog_apm_instrumentation_libraries: [ "java" ]
