---
- name: Set APM injection install packages
  set_fact:
    _dd_apm_install_pkgs: "{{ (_dd_apm_install_pkgs | default([])) + ['datadog-apm-library-' + item] }}"
  with_items: "{{ datadog_apm_instrumentation_languages }}"

- name: Install APM inject libraries
  apt:
    name: "{{ ['datadog-apm-inject'] + (_dd_apm_install_pkgs | default([])) }}"
    state: latest # noqa package-latest
    update_cache: true
    cache_valid_time: "{{ datadog_apt_cache_valid_time }}"
