---
- name: Remove "all" tracer package if installed
  apt:
    name: datadog-apm-inject-all
    state: absent

- name: Override "all" to explicitly specify each tracer
  set_fact:
    datadog_apm_instrumentation_languages: ["java", "node", "dotnet", "python", "ruby"]
  when: datadog_apm_instrumentation_languages == ["all"]

- name: Set APM injection install packages
  set_fact:
    agent_dd_apm_install_pkgs: "{{ (agent_dd_apm_install_pkgs | default([], true)) + ['datadog-apm-library-' + item] }}"
  with_items: "{{ datadog_apm_instrumentation_languages }}"

- name: Install APM inject libraries
  apt:
    name: "{{ ['datadog-apm-inject'] + (agent_dd_apm_install_pkgs | default([], true)) }}"
    state: latest # noqa package-latest
    update_cache: true
    cache_valid_time: "{{ datadog_apt_cache_valid_time }}"
