---
- name: Set APM injection languages and versions for Debian
  set_fact:
    agent_dd_apm_install_pkgs: "{{ (agent_dd_apm_install_pkgs |
      default([], true)) + ['datadog-apm-library-' + (item | regex_replace('[:]', '='))] }}"
    package_state: present
  loop: "{{ datadog_apm_instrumentation_lib_versions }}"
  when: datadog_apm_instrumentation_lib_versions

- name: Set APM injection install packages
  set_fact:
    agent_dd_apm_install_pkgs: "{{ (agent_dd_apm_install_pkgs | default([], true)) +
      ['datadog-apm-library-' + item] }}"
    package_state: latest
  with_items: "{{ datadog_apm_instrumentation_languages }}"
  when: not datadog_apm_instrumentation_lib_versions

- name: Install APM inject libraries
  apt:
    name: "{{ ['datadog-apm-inject'] + (agent_dd_apm_install_pkgs | default([], true)) }}"
    state: "{{ (package_state | default('latest')) }}"
    update_cache: true
    cache_valid_time: "{{ datadog_apt_cache_valid_time }}"

- name: Show tracers to install
  debug:
    msg: "Installed tracers: {{ agent_dd_apm_install_pkgs }}"
