---
- name: Install the APM inject library
  apt:
    name: datadog-apm-inject
    state: latest # noqa 403
    update_cache: yes
    cache_valid_time: "{{ datadog_apt_cache_valid_time }}"

- name: Install the APM inject language libraries
  apt:
    name: "datadog-apm-library-{{ item }}"
    state: latest # noqa 403
    update_cache: yes
    cache_valid_time: "{{ datadog_apt_cache_valid_time }}"
  with_items: "{{ datadog_apm_libraries }}"
