---
- name: Install latest datadog-agent package
  apt:
    name: "{{ datadog_agent_flavor }}"
    state: latest # noqa package-latest
    update_cache: true
    cache_valid_time: "{{ datadog_apt_cache_valid_time }}"
  register: agent_datadog_agent_install
  when: not ansible_check_mode
