---
- name: Install Datadog installer (apt)
  ansible.builtin.apt:
    name: "{{ datadog_installer_flavor }}"
    state: latest # noqa package-latest
    update_cache: true
    cache_valid_time: "{{ datadog_apt_cache_valid_time }}"
  register: datadog_installer_install_result
  ignore_errors: true
