---
# This file doesn't actually contain "handlers" in the Ansible sense: when running
# our role, Ansible only loads the contents of handlers/main.yml as handlers.
# However, this is here because this is a "handler-like" task that is dynamically
# included by a handler task in handlers/main.yml.
- name: Restart Windows datadogagent service
  win_service:
    name: datadogagent
    state: restarted
    force_dependent_services: true
  when: datadog_enabled and not ansible_check_mode and ansible_facts.os_family == "Windows"
