---
# TODO: @adam.schneider - Make this generic
- name: Build APM library installation payloads
  set_fact:
    telemetry_payload: 
      "{{ telemetry_payload | default([]) + 
          [{'specified_' + item.split(':')[0] + '_lib_version':
              item.split(':')[1] | default('default')
          }] }}"
  loop: "{{ datadog_apm_instrumentation_libraries }}"

- name: Build APM library installation payloads for telemetry
  set_fact:
    telemetry_payload: 
      "{{ telemetry_payload | default([]) + 
          [{'specified_' + item.split(':')[0] + '_lib_version':
              item.split(':')[1] | default('default')
          }] }}"
  loop: "{{ datadog_apm_instrumentation_libraries }}"

- name: Build telemetry request
  set_fact:
    telemetry_request:
      request_type: 'apm-onboarding-event'
      api_version: 'v2'
      payload:
        event_name: 'agent.injection.success'
        tags: "{{ telemetry_payload }}"
      host:
        hostname: "{{ ansible_hostname }}"
        os: 'GNU/Linux'
        os_version: "{{ ansible_facts.os_family }}"
        architecture: "{{ ansible_facts.architecture }}"