# Check current state of the integration

- name: Check integration state, integration={{ item.key }}
  command:
    argv:
      - "{{ datadog_agent_binary_path }}"
      - integration
      - show
      - -q
      - "{{ item.key }}"
  register: integration_version
  failed_when: false # This task is supposed to fail when the integration is not installed
  changed_when: false

# Remove integration

- name: Removing integration, integration={{ item.key }}
  command:
    argv:
      - "{{ datadog_agent_binary_path }}"
      - integration
      - remove
      - "{{ item.key }}"
  become: true
  become_user: "{{ integration_command_user }}"
  when:
    - item.value.action == "remove"
    - integration_version.rc == 0
  changed_when: true

# Install integration

- name: Installing pinned version of integration, integration={{ item.key }}
  command: "{{ datadog_agent_binary_path }} integration install {{ third_party }} {{ item.key }}=={{ item.value.version }}"
  become: true
  become_user: "{{ integration_command_user }}"
  vars:
    third_party: "{% if 'third_party' in item.value and item.value.third_party | bool %}--third-party{% endif %}"
  when:
    - item.value.action == "install"
    - integration_version.stdout | trim != item.value.version
  changed_when: true
