# Check current state of the integration

- name: Check {{ item.key }} integration state
  command:
    argv:
      - "{{ datadog_agent_binary_path }}"
      - integration
      - show
      - -q
      - "{{ item.key }}"
  register: integration_version
  failed_when: false # This task is supposed to fail when the integration is not installed
  changed_when: false

# Remove integration

- name: Removing {{ item.key }} integration
  command:
    argv:
      - "{{ datadog_agent_binary_path }}"
      - integration
      - remove
      - "{{ item.key }}"
  become: yes
  become_user: "{{ integration_command_user }}"
  when: 
    - item.value.action == "remove"
    - integration_version.stdout | length > 0

# Install integration

- name: Installing pinned version of {{ item.key }} integration
  command: "{{ datadog_agent_binary_path }} integration install {{ third_party }} {{ item.key }}=={{ item.value.version }}"
  become: yes
  become_user: "{{ integration_command_user }}"
  vars:
    third_party: "{% if 'third_party' in item.value and item.value.third_party | bool %}--third-party{% endif %}"
  when:
    - item.value.action == "install"
    - integration_version.stdout | trim != item.value.version
