---
# Remove integrations

- name: Removing integrations # noqa no-changed-when Will be fixed in another pending PR
  command:
    argv:
      - "{{ datadog_agent_binary_path }}"
      - integration
      - remove
      - "{{ item.key }}"
  become: true
  become_user: "{{ integration_command_user }}"
  loop: "{{ datadog_integration | dict2items }}"
  when: item.value.action == "remove"

# Install integrations

- name: Installing pinned version of integrations # noqa no-changed-when Will be fixed in another pending PR
  command: "{{ datadog_agent_binary_path }} integration install {{ third_party }} {{ item.key }}=={{ item.value.version }}"
  become: true
  become_user: "{{ integration_command_user }}"
  vars:
    third_party: "{% if 'third_party' in item.value and item.value.third_party | bool %}--third-party{% endif %}"
  loop: "{{ datadog_integration | dict2items }}"
  when: item.value.action == "install"
