---
- name: Set Agent binary path
  set_fact:
    datadog_agent_binary_path: "{{ datadog_agent_binary_path_windows }}"

- name: Set Agent user for integration commmand
  set_fact:
    integration_command_user: "{{ integration_command_user_windows }}"

- name: Include integration installation and removal tasks
  include_tasks: integration/_windows-integration-update.yml
  loop: "{{ datadog_integration | dict2items }}"
